Added Code For Implementation of Stack Using Linkedlist
Sujal-2820/Hacktoberfest-DSA pull request #8
Opened 2023-10-17 14:26 UTC by Manav39

2023-10-17 19:15 UTC, Kishan101101 requested changes
adding stack

2023-10-17 19:16 UTC, Kishan101101 approved these changes

2023-10-18 04:33 UTC, Sujal-2820 reviewed
Hey @Manav39 can you delete the tasks.json file. It's actually not needed here. 

Good job BTW 💯

2023-10-18 14:55 UTC, Sujal-2820 approved these changes

2023-10-18 14:55 UTC, merged